#!/usr/bin/env python

import sys
import itertools

for i in range(1, len(sys.argv)):
    search = []
    words = sys.argv[i].split()

    for perm in itertools.permutations(words):
        search.append(perm)

    for item in search:
        print '"' + ''.join(item) + '" OR',
        print '"' + ' '.join(item) + '" OR',
        print '"' + ''.join(item).upper() + '" OR',
        print '"' + ' '.join(item).upper() + '" OR',
