#!/usr/bin/env python
#-------------------------------------------------------------------------------
# extract ledjam radio "now playing" information
#
# references:
#
#   http://www.smackfu.com/stuff/programming/shoutcast.html
#   http://anton.logvinenko.name/en/blog/how-to-get-title-from-audio-stream-with-python.html
#-------------------------------------------------------------------------------

import urllib2
import re
import argparse

parser = argparse.ArgumentParser(description=
  'display shoutcast stream "now playing" info')

parser.add_argument('url', metavar='URL', type=str,
    help='shoutcast stream url')

args = parser.parse_args()

pattern = re.compile(r'''StreamTitle='(\[.*\] )?(?P<title>[\w\W\-]*?)';''')

request = urllib2.Request(args.url)
request.add_header('Icy-MetaData', 1)
response = urllib2.urlopen(request)
header = response.headers.get('icy-metaint')

if header is not None:
  metadata = int(header)
  content = response.read(metadata + 255)
  print re.search(pattern, content[metadata:]).group('title')
