#!/usr/bin/env python
#-------------------------------------------------------------------------------
# extract ledjam radio "now playing" information
#
# references:
#
#   http://www.smackfu.com/stuff/programming/shoutcast.html
#   http://anton.logvinenko.name/en/blog/how-to-get-title-from-audio-stream-with-python.html
#-------------------------------------------------------------------------------

import urllib2

request = urllib2.Request('http://www.ledjamradio.com/sound')
request.add_header('Icy-MetaData', 1)
response = urllib2.urlopen(request)
header = response.headers.get('icy-metaint')
if header is not None:
  metadata = int(header)
  content = response.read(metadata + 255)
  title = content[metadata:].split("'")[1]
  artist, track = title.split(" - ")
  print artist.strip()
  print track.strip()
